aboutCompany/urls.py
from django.urls import path
from . import views

app_name = "about-us"
urlpatterns = [
    path('', views.aboutUs, name='aboutUs'),
]

availability/urls.py
from django.urls import re_path
from . import views

app_name = "services"
urlpatterns = [
    re_path(r'^$', views.product_list, name='product_list'),
    re_path(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
]

main/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.renderIndex, name="index")
]

marco/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('contact/', include('contact.urls')),
    path('service/', include('availability.urls', namespace='availability')),
    path('process/', include('mediabank.urls', namespace='mediabank')),
    path('order/', include('order.urls', namespace='order')),
    path('about-us/', include('aboutCompany.urls', namespace='aboutUs'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mediabank/urls.py
from django.urls import path
from . import views

app_name = "mediabank"
urlpatterns = [
    path('', views.media_photo, name='media_photo'),
]

order/urls.py
from django.urls import path
from . import views

app_name = "order"
urlpatterns = [
    path('', views.order_service, name='order_service'),
]

main/views.py
from django.shortcuts import render

def renderIndex(request):
    return render(request, 'main/home.html', {})

main/templates/main/home.html
{% extends 'main/index.html' %} {% load static %}
{% block title %}Главная страница{% endblock %}
{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/>
{% endblock %}
{% block content %}
    <div class="wrapper__home">
        <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active" data-bs-interval="2000">
                    <img src={% static 'media/images/carousel1.jpg' %} alt="image" width="1920" height="780"/>
                </div>
                <div class="carousel-item" data-bs-interval="5000">
                    <img src={% static 'media/images/carousel2.jpg' %} alt="image" width="1920" height="780"/>
                </div>
                <div class="carousel-item" data-bs-interval="5000">
                    <img src={% static 'media/images/carousel3.jpg' %} alt="image" width="1920" height="780"/>
                </div>
                <div class="carousel-item" data-bs-interval="5000">
                    <img src={% static 'media/images/carousel4.jpg' %} alt="image" width="1920" height="780"/>
                </div>
                <div class="carousel-item" data-bs-interval="5000">
                    <img src={% static 'media/images/carousel5.jpg' %} alt="image" width="1920" height="780"/>
                </div>
                <div class="carousel-item" data-bs-interval="5000">
                    <img src={% static 'media/images/carousel6.jpg' %} alt="image" width="1920" height="780"/>
                </div>
            </div>
        </div>
        <div class="carousel-info">
            <h1>Студия печати на Космонавтов Marcografika</h1>
            <ul>
                <li>Услуги типографии, фотопечать, cувенирная продукция</li>
                <li>Качественная печать любой сложности</li>
                <li>Опытные специалисты</li>
                <li>Приемлемые цены</li>
            </ul>
            <a href="{% url "order:order_service" %}">Сделать заказ</a>
        </div>
        <div class="sections">
            <div class="sections__item">
                <div class="sections__row">
                    <h2>Услуги</h2>
                </div>
                <div class="sections__row">
                    <div class="item__images">
                        <img src={% static 'media/images/carousel1.jpg' %} alt="photo" width="274" height="274"/>
                    </div>
                    <div class="item__images">
                        <img src={% static 'media/images/carousel1.jpg' %} alt="photo" width="274" height="274"/>
                    </div>
                    <div class="item__images">
                        <img src={% static 'media/images/carousel1.jpg' %} alt="photo" width="274" height="274"/>
                    </div>
                    <div class="item__link service">
                        <a href="{% url "availability:product_list" %}">Услуги</a>
                        <img src={% static 'media/icons/right-arrow.svg' %} alt="photo" width="20" height="20"/>
                    </div>
                </div>
            </div>
            <div class="sections__item">
                <div class="sections__row">
                    <h2>Процесс</h2>
                </div>
                <div class="sections__row">
                    <div class="item__images">
                        <img src={% static 'media/images/carousel1.jpg' %} alt="photo" width="274" height="274"/>
                    </div>
                    <div class="item__images">
                        <img src={% static 'media/images/carousel1.jpg' %} alt="photo" width="274" height="274"/>
                    </div>
                    <div class="item__images">
                        <img src={% static 'media/images/carousel1.jpg' %} alt="photo" width="274" height="274"/>
                    </div>
                    <div class="item__link process">
                        <a href="{% url "mediabank:media_photo" %}">Процесс</a>
                        <img src={% static 'media/icons/right-arrow.svg' %} alt="photo" width="20" height="20"/>
                    </div>
                </div>
            </div>
            <div class="sections__item">
                <div class="sections__row">
                    <h2>О нас</h2>
                </div>
                <div class="sections__row">
                    <div class="item__images">
                        <img src={% static 'media/images/carousel1.jpg' %} alt="photo" width="274" height="274"/>
                    </div>
                    <div class="item__images">
                        <img src={% static 'media/images/carousel1.jpg' %} alt="photo" width="274" height="274"/>
                    </div>
                    <div class="item__images">
                        <img src={% static 'media/images/carousel1.jpg' %} alt="photo" width="274" height="274"/>
                    </div>
                    <div class="item__link about-company">
                        <a href>О нас</a>
                        <img src={% static 'media/icons/right-arrow.svg' %} alt="photo" width="20" height="20"/>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block footer %}
    <footer class="home">
        <div class="footer__container">
            <div class="container__content">
                <div class="content">
                    <a href="{% url 'index' %}">
                        <img src={% static "media/icons/logo.png" %} alt="logo" width="220" height="40"/>
                    </a>
                    <span class="date">© 2017-2021, OOO MARCOGRAFIKA</span>
                    <div class="social-networks footer">
                        <a href="https://www.instagram.com/marcografika/">
                            <img src={% static 'media/icons/instagram.svg' %} alt="instagram" width="40" height="40"/>
                        </a>
                        <a href="https://vk.com/fotobulak">
                            <img src={% static "media/icons/vk.svg" %} alt="vk" width="40" height="40"/>
                        </a>
                        <a href="https://www.youtube.com/channel/UCOu3eWZ0Zh5aUSvfHqGnnZQ">
                            <img src={% static "media/icons/youtube.svg" %} alt="youtube" width="40" height="40"/>
                        </a>
                    </div>
                </div>
                <div class='scroll-to-top'>
                    <img src={% static "media/icons/to-top.svg" %} alt="logo" width="15" height="15"/>
                </div>
                <script type="text/javascript">
                    $('.scroll-to-top').click(function () {
                        $(window).scrollTop(0);
                    });

                </script>
            </div>
        </div>
    </footer>
{% endblock %}

main/templates/main/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock%}</title>

    <link rel="icon" type="image/x-icon" href={% static 'media/icons/favicon.ico' %}>
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    {%block styles%}{%endblock%}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
        crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    {%block scripts%}{%endblock%}
</head>

<body {% if "media" in request.path%} class="overflow-hidden" {%endif%}>
    <header>
        <div class="header__container">
            <div class="container__wrapper">
                <div class="container__logo-social">
                    <div class="logo">
                        <a href="{%url 'index' %}">
                            <img src={% static 'media/icons/logo.png' %} alt="logo" width="220" height="40" />
                        </a>
                    </div>
                    <div class="social">
                        <a href="{% url "order:order_service" %}" class="button">Оформить заказ</a>
                        <a href="mailto:marco1192@mail.ru">marco1192@mail.ru</a>
                        <a href="tel:+79870690441">+7 988 888 8888</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="container__links">
            <nav class="links__content">
                <a href="{%url 'index' %}" {% if request.path == '/' %} class="active" {% endif %}>Главная
                    страница</a>
                <a href="{% url "availability:product_list" %}" {% if 'service' in request.path %} class="active" {%endif %}>Услуги</a>
                <a href="{% url "mediabank:media_photo" %}" {% if 'process' in request.path %} class="active" {%endif%}>Процесс</a>
                <a href="{% url "aboutUs:aboutUs" %}" {% if 'about-us' in request.path %} class="active" {%endif %}>О нас</a>
                <a href="{% url "contact" %}" {% if 'contact' in request.path %} class="active" {%endif %}>Контакты</a>
            </nav>
        </div>
        <script type="text/javascript">
            let header = $('.container__links'),
                scrollPrev = 0;
            $(window).scroll(function () {
                let scrolled = $(window).scrollTop();


                if (scrolled > 100 && scrolled > scrollPrev) {
                    header.addClass('out');
                } else {
                    header.removeClass('out');
                }
                scrollPrev = scrolled;
            });
        </script>
        </div>
    </header>
    <div class="main-wrapper">
        {% block content %}{% endblock %}
    </div>
    {%block footer%}{%endblock%}
    <div class="menu">
        <button class="nav-tgl" type="button" aria-label="toggle menu">
            <span aria-hidden="true"></span>
        </button>
        <nav id="overlay" class="hamburger">
            <div class="hamburger__header">
                <a href="{%url 'index' %}">
                    <img src={% static 'media/icons/logo.png' %} alt="logo" width="220" height="40" />
                </a>
            </div>
            <div class="hamburger__content">
                <ul>
                    <li>
                        <a href="{%url 'index' %}" {% if request.path == '/' %} class="active" {% endif %}>Главная
                            страница</a>
                    </li>

                    <li>
                        <a href="{% url "availability:product_list" %}" {% if 'service' in request.path %}
                            class="active" {% endif %}>Услуги</a>
                    </li>

                    <li>
                        <a href="{% url "mediabank:media_photo" %}" {% if 'process' in request.path %} class="active"
                            {%endif %}>Процесс</a>
                    </li>

                    <li>
                        <a href="{% url "aboutUs:aboutUs" %}" {% if 'about-us' in request.path %} class="active" {%endif %}>О нас</a>
                    </li>
                    <li>
                        <a href="{% url "contact" %}" {% if 'contact' in request.path %} class="active" {%endif%}>Контакты</a>
                    </li>
                </ul>
                <div class="hamburger__information">
                    <a href="mailto:marco1192@mail.ru">marco1192@mail.ru</a>
                    <a href="tel:+79870690441">+7 988 888 8888</a>
                    <a
                        href="https://yandex.ru/maps/43/kazan/house/ulitsa_kosmonavtov_71/YEAYdAdpQEwOQFtvfXt4d3lmYw==/?ll=49.209998%2C55.796557&z=17.22">Ул.
                        Космонавтов, 71, Казань, Респ. Татарстан, 420061</a>
                    <div class="social-networks">
                        <a href="https://www.instagram.com/marcografika/">
                            <img src={% static 'media/icons/instagram.svg' %} alt="instagram" width="40" height="40" />
                        </a>
                        <a href="https://vk.com/fotobulak">
                            <img src={% static "media/icons/vk.svg" %} alt="vk" width="40" height="40" />
                        </a>
                        <a href="https://www.youtube.com/channel/UCOu3eWZ0Zh5aUSvfHqGnnZQ">
                            <img src={% static "media/icons/youtube.svg" %} alt="youtube" width="40" height="40" />
                        </a>
                    </div>
                </div>
                <script type="text/javascript">
                    const menu = document.querySelector('.menu');
                    const btn = menu.querySelector('.nav-tgl');
                    btn.addEventListener('click', evt => {
                        menu.classList.toggle('active');
                        if ($('.menu').hasClass('active')) {
                            $('body').addClass('no-overflow')
                         } else {$('body').removeClass('no-overflow')}
                    })
                </script>
            </div>
        </nav>
    </div>
</body>

</html>